from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from torneo.autenticacion import VistaDeIngreso
from torneo.views import (
    acf,
    asistente,
    calendario,
    categoria,
    diagnostico,
    equipos,
    escuela,
    fixture,
    inicio,
    jugadores,
    mas,
    mover,
    personas,
    png,
    programar,
    pwa,
    reglas,
    reprogramar,
    torneo,
)
from torneo.views import publico as vistas_publicas
from torneo.views.publicar import publicar

urlpatterns = [
    path("", inicio, name="inicio"),
    path("manifest.webmanifest", pwa.manifest, name="manifest"),
    path("sw.js", pwa.service_worker, name="service-worker"),
    path("mas/", mas, name="mas"),
    path("personas/nueva/", personas.nueva, name="nueva-persona"),
    path("personas/<int:pk>/rol/", personas.rol, name="rol-persona"),
    path("calendario/", calendario.calendario, name="calendario"),
    path("calendario/agregar-dia/", calendario.agregar_dia, name="agregar-dia"),
    path("calendario/club/", calendario.elegir_club, name="elegir-club"),
    path("calendario/club/<int:pk>/", calendario.por_club, name="calendario-club"),
    path("calendario/<str:fecha>/", calendario.calendario_dia, name="calendario-dia"),
    path("calendario/<str:fecha>/suspender/", calendario.suspender, name="suspender-dia"),
    path("calendario/<str:fecha>/png/", png.png, name="png-dia"),
    path("escuela/", escuela, name="escuela"),
    path("torneo/", torneo, name="torneo"),
    path("torneo/<int:pk>/equipos/nuevo/", equipos.nuevo_equipo, name="nuevo-equipo"),
    path("torneo/<int:pk>/fixture/generar/", fixture.generar, name="generar-fixture"),
    path("torneo/<int:pk>/series/", fixture.guardar_series, name="guardar-series"),
    path("torneo/<int:pk>/<str:pestana>/", categoria, name="categoria"),
    path("equipos/<int:pk>/jugadores/nuevo/", jugadores.agregar_jugador, name="agregar-jugador"),
    path("equipos/<int:pk>/jugadores/revisar/", jugadores.revisar_jugador, name="revisar-jugador"),
    path("equipos/<int:pk>/profes/nuevo/", jugadores.agregar_profe, name="agregar-profe"),
    path("equipos/<int:pk>/profes/revisar/", jugadores.revisar_profe, name="revisar-profe"),
    path("equipos/<int:pk>/<str:seccion>/", equipos.equipo, name="equipo"),
    path("jugadores/<int:pk>/verificar/", jugadores.verificar, name="verificar"),
    path("partidos/<int:pk>/mover/", mover.mover, name="mover"),
    path("partidos/<int:pk>/asignar/", fixture.asignar, name="asignar-eliminacion"),
    path("torneos/nuevo/", asistente.empezar, name="crear-torneo"),
    path("torneos/nuevo/<int:paso>/", asistente.asistente, name="asistente"),
    path("torneos/<int:pk>/reglas/", reglas, name="reglas"),
    path("torneos/<int:pk>/publico/", publicar, name="publicar"),
    path("torneos/<int:pk>/fixtures/", fixture.generar_todos, name="generar-fixtures"),
    path("torneos/<int:pk>/programar/", programar.programar, name="programar"),
    path("torneos/<int:pk>/acf/", acf.acf, name="acf"),
    path("torneos/<int:pk>/acf/revisar/", acf.revisar, name="revisar-acf"),
    path("bloqueos/<int:pk>/borrar/", acf.borrar, name="borrar-bloqueo"),
    path("bloqueos/<int:pk>/propuestas/", reprogramar.propuestas, name="propuestas"),
    path("corridas/<int:pk>/propuestas/", reprogramar.ver_propuestas, name="ver-propuestas"),
    path(
        "corridas/<int:pk>/aplicar/<int:indice>/",
        reprogramar.aplicar_propuesta,
        name="aplicar-propuesta",
    ),
    path("t/<int:pk>/", vistas_publicas.publico, name="publico"),
    path(
        "t/<int:pk>/<int:categoria>/<str:pestana>/",
        vistas_publicas.categoria,
        name="publico-categoria",
    ),
    # Con la sesión iniciada, el login lleva al inicio. Tiene límite de intentos (T6.3).
    path("cuentas/login/", VistaDeIngreso.as_view(), name="login"),
    path("cuentas/logout/", auth_views.LogoutView.as_view(), name="logout"),
    # Sin recuperación por correo: no hay correo configurado (T6.3).
    path(
        "cuentas/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "cuentas/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("diagnostico/componentes/", diagnostico.componentes, name="diagnostico-componentes"),
    path("admin/", admin.site.urls),
]
