# Generated by Django 6.1.2 on 2026-10-07 05:22

import django.db.models.deletion
import torneo.models.configuracion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("edicion", models.PositiveSmallIntegerField()),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("inicio", models.DateField()),
                ("fin", models.DateField()),
                ("zona_horaria", models.CharField(default="America/La_Paz", max_length=50)),
                (
                    "descanso_min",
                    models.PositiveSmallIntegerField(default=5, verbose_name="descanso (min)"),
                ),
                (
                    "cambio_entre_partidos_min",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="cambio entre partidos (min)"
                    ),
                ),
                (
                    "cuerpo_tecnico",
                    models.JSONField(
                        default=torneo.models.configuracion._cuerpo_tecnico_por_defecto
                    ),
                ),
                (
                    "reglas",
                    models.JSONField(default=torneo.models.configuracion._reglas_por_defecto),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("fin__gte", models.F("inicio"))),
                        name="torneo_fin_despues_de_inicio",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es la mitad de otra cancha. La cancha entera ocupa sus mitades.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitades",
                        to="torneo.cancha",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canchas",
                        to="torneo.torneo",
                    ),
                ),
            ],
            options={
                "ordering": ["torneo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Franja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("entre_semana", "Entre semana (para reprogramar)"),
                        ],
                        default="regular",
                        max_length=12,
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franjas",
                        to="torneo.torneo",
                    ),
                ),
            ],
            options={
                "ordering": ["torneo", "inicio"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("fin__gt", models.F("inicio"))),
                        name="franja_fin_despues_de_inicio",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoriaNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("categoria", models.CharField(max_length=50)),
                ("edad", models.PositiveSmallIntegerField(help_text="La N de «Sub N»")),
                (
                    "anios_nacimiento",
                    models.PositiveSmallIntegerField(default=1, verbose_name="años de nacimiento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("mixto", "Mixto"), ("F", "Femenino")],
                        default="mixto",
                        max_length=5,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("unico", "Único"),
                            ("inicial", "Inicial"),
                            ("avanzado", "Avanzado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("F5", "Fútbol 5"),
                            ("F7", "Fútbol 7"),
                            ("F8", "Fútbol 8"),
                            ("F11", "Fútbol 11"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "min_jugadores",
                    models.PositiveSmallIntegerField(verbose_name="mínimo de jugadores"),
                ),
                (
                    "max_jugadores",
                    models.PositiveSmallIntegerField(verbose_name="máximo de jugadores"),
                ),
                (
                    "min_por_tiempo",
                    models.PositiveSmallIntegerField(verbose_name="minutos por tiempo"),
                ),
                ("convocados_por_partido", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "canchas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categorias",
                        to="torneo.cancha",
                        verbose_name="canchas compatibles",
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="torneo.torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría-nivel",
                "verbose_name_plural": "categorías-nivel",
                "ordering": ["torneo", "edad", "categoria", "nivel"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("torneo", "categoria", "nivel"), name="categoria_nivel_unica"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_jugadores__gte", models.F("min_jugadores"))),
                        name="max_jugadores_no_menor_que_min",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cancha",
            constraint=models.UniqueConstraint(
                fields=("torneo", "codigo"), name="codigo_de_cancha_unico"
            ),
        ),
    ]
