# Generated by Django 6.1.2 on 2026-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_configuracion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='torneo',
            constraint=models.UniqueConstraint(fields=('nombre', 'anio'), name='torneo_unico_por_anio'),
        ),
    ]
