# Generated by Django 6.1.2 on 2026-10-07 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_torneo_unico_por_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='JMP Soccer School', max_length=80)),
                ('color_primario', models.CharField(default='#059669', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Tiene que ser un color hexadecimal, como #059669.')])),
            ],
            options={
                'verbose_name': 'organizador',
                'verbose_name_plural': 'organizador',
            },
        ),
    ]
