# Generated by Django 6.1.2 on 2026-10-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_organizador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'permissions': [('configurar_torneo', 'Crear torneos y cambiar su configuración'), ('programar_partidos', 'Programar y reprogramar partidos'), ('inscribir_equipos', 'Cargar equipos y listas'), ('verificar_jugadores', 'Verificar a los jugadores con su documento')]},
        ),
    ]
