# Generated by Django 6.1.2 on 2026-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_grupos_de_los_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='publico',
            field=models.BooleanField(default=False, help_text='Si se ve sin login en /t/<id>/ (sin datos personales)', verbose_name='público'),
        ),
    ]
