# Generated by Django 6.1.2 on 2026-10-07 20:03

import django.core.validators
import re
import torneo.models.sitio
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def del_verde_al_azul(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """El verde era el valor por defecto rechazado (2026-10-07), no una elección."""
    apps.get_model("torneo", "Organizador").objects.filter(color_primario="#059669").update(
        color_primario="#0d2440"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_torneo_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='color_acento',
            field=models.CharField(default='#f2cf3a', help_text='Lo que resalta: la pestaña activa, la selección y el año del torneo.', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#[0-9a-fA-F]{6}$'), 'Tiene que ser un color hexadecimal, como #0d2440.')], verbose_name='color de acento'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='color_primario',
            field=models.CharField(default='#0d2440', help_text='La barra superior, la banda y los botones principales. Con texto blanco encima.', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^#[0-9a-fA-F]{6}$'), 'Tiene que ser un color hexadecimal, como #0d2440.'), torneo.models.sitio._se_lee_texto_blanco], verbose_name='color principal'),
        ),
        migrations.RunPython(del_verde_al_azul, migrations.RunPython.noop),
    ]
