# Generated by Django 6.1.2 on 2026-10-07 20:23

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import torneo.models.inscripcion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_colores_del_organizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('alias', models.JSONField(blank=True, default=list, validators=[torneo.models.inscripcion._validar_alias])),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='club_nombre_unico')],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre visible')),
                ('color_1', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Tiene que ser un color hexadecimal, como #c8102e.')], verbose_name='color 1')),
                ('color_2', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Tiene que ser un color hexadecimal, como #c8102e.')], verbose_name='color 2')),
                ('pagado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='torneo.categorianivel')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='torneo.club')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('', 'Pendiente'), ('ci', 'CI'), ('ci_extranjero', 'CI de extranjero'), ('pasaporte', 'Pasaporte')], default='', max_length=13)),
                ('documento', models.CharField(blank=True, help_text='Como se muestra', max_length=30)),
                ('clave_documento', models.CharField(blank=True, help_text='Para comparar (dominio.documentos)', max_length=30)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave_documento', ''), _negated=True), fields=('clave_documento',), name='documento_unico_si_existe')],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False, help_text='La mesa vio el documento (INS-12)')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneo.equipo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='torneo.persona')),
            ],
            options={
                'verbose_name_plural': 'jugadores',
                'ordering': ['equipo', 'dorsal'],
            },
        ),
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(help_text='Uno de los roles del cuerpo técnico', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profes', to='torneo.equipo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profes', to='torneo.persona')),
            ],
            options={
                'ordering': ['equipo', 'rol'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('club', 'categoria', 'nombre'), name='equipo_unico_por_club_y_categoria'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('equipo', 'persona'), name='jugador_una_vez'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('dorsal__isnull', False)), fields=('equipo', 'dorsal'), name='dorsal_unico_en_el_equipo'),
        ),
        migrations.AddConstraint(
            model_name='profe',
            constraint=models.UniqueConstraint(fields=('equipo', 'persona'), name='profe_una_vez'),
        ),
    ]
