# Generated by Django 6.1.2 on 2026-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_inscripcion'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='equipo',
            name='equipo_unico_por_club_y_categoria',
            constraint=models.UniqueConstraint(fields=('club', 'categoria', 'nombre'), name='equipo_unico_por_club_y_categoria', violation_error_message='Ya hay un equipo con ese nombre, de ese club, en esa categoría.'),
        ),
    ]
