# Generated by Django 6.1.2 on 2026-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_mensaje_equipo_repetido'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='es_demo',
            field=models.BooleanField(default=False, help_text='Datos inventados por generar_demo; se pueden rehacer', verbose_name='de demo'),
        ),
    ]
