# Generated by Django 6.1.2 on 2026-10-07 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0010_torneo_es_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='torneo.categorianivel')),
                ('equipos', models.ManyToManyField(related_name='series', to='torneo.equipo')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('grupos', 'Fase de grupos'), ('eliminacion', 'Eliminación')], max_length=11)),
                ('copa', models.CharField(blank=True, max_length=6)),
                ('ronda', models.CharField(blank=True, max_length=5)),
                ('clave', models.CharField(blank=True, max_length=30)),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('fecha', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('texto_local', models.CharField(blank=True, max_length=80)),
                ('texto_visitante', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Sin programar'), ('programado', 'Programado'), ('jugado', 'Jugado')], default='pendiente', max_length=10)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fijado', models.BooleanField(default=False, help_text='Fijado a mano: no se mueve (PRO-10)')),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='torneo.cancha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneo.categorianivel')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='torneo.equipo')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='torneo.equipo')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='torneo.serie')),
            ],
            options={
                'ordering': ['categoria', 'fase', 'fecha', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='serie_unica'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('local', models.F('visitante')), _negated=True), ('local__isnull', True), ('visitante__isnull', True), _connector='OR'), name='local_distinto_de_visitante'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.UniqueConstraint(condition=models.Q(('clave', ''), _negated=True), fields=('categoria', 'clave'), name='clave_de_partido_unica'),
        ),
    ]
