# Generated by Django 6.1.2 on 2026-10-08 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_fixture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('programar', 'Programar'), ('reprogramar', 'Reprogramar')], default='programar', max_length=11)),
                ('estado', models.CharField(choices=[('corriendo', 'Corriendo'), ('terminada', 'Terminada'), ('fallida', 'Falló')], default='corriendo', max_length=9)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='duración (s)')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='torneo.torneo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
