# Generated by Django 6.1.2 on 2026-10-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0012_corrida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(default='Partido de la ACF', max_length=80)),
                ('equipos', models.ManyToManyField(related_name='bloqueos', to='torneo.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='torneo.torneo')),
            ],
            options={
                'ordering': ['inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='bloqueo_fin_despues_de_inicio')],
            },
        ),
    ]
