# Generated by Django 6.1.2 on 2026-10-08 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0013_bloqueo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_antes', models.DateTimeField(blank=True, null=True)),
                ('inicio_despues', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('cancha_antes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='torneo.cancha')),
                ('cancha_despues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='torneo.cancha')),
                ('corrida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios', to='torneo.corrida')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='torneo.partido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
    ]
