# Generated by Django 6.1.2 on 2026-10-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0014_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='franja',
            name='suspendida',
            field=models.BooleanField(default=False, help_text='Por lluvia u otro motivo: no se programa nada en ella'),
        ),
    ]
